services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      front:
        condition: service_completed_successfully

  front:
    image: seonghun120614/next-skillary:latest
    build:
      context: ./next-skillary-front
      dockerfile: Dockerfile
    env_file: .env.front
    depends_on:
      back:
        condition: service_completed_successfully

  back:
    image: seonghun120614/spring-skillary:latest
    build:
      context: ./spring-skillary-back
      dockerfile: Dockerfile
    env_file: .env.back
    depends_on:
      db:
        condition: service_healthy

  db:
    image: seonghun120614/mysql-skillary:latest
    env_file: .env.db
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s

volumes:
  db_data: