spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secret: "this-is-very-secret-key-for-jwt-signing-please-change-it"

    expire-time:
      access: 1800
      refresh: 604800

#  JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_ACCESS_SECRET_KEY }}
#  JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_REFRESH_SECRET_KEY }}