spring:
    application:
        name: spring-skillary-back
    servlet:
      multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 200MB
        file-size-threshold: 2KB
    mail:
      host: ${SPRING_MAIL_HOST}
      port: ${SPRING_MAIL_PORT}
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

app:
  mail:
    from: ${APP_MAIL_FROM}
    subject: ${APP_MAIL_SUBJECT}
    code-expiry-minutes: ${APP_MAIL_CODE_EXPIRY_MINUTES}

  jwt:
    secret: ${JWT_SECRET_KEY}
    expire-time:
      access: ${JWT_EXPIRE_TIME_ACCESS}
      refresh: ${JWT_EXPIRE_TIME_REFRESH}

# AWS S3 설정 (환경 변수)
aws:
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
    s3:
        bucket-name: ${AWS_S3_BUCKET_NAME:skillary-s3}
        region: ${AWS_S3_REGION:ap-northeast-2}
        base-url: ${AWS_S3_BASE_URL:}  # s3 파일서버 별도 도에인 있는 경우 (없어서 빈값)
