spring:
    application:
        name: spring-skillary-back
    servlet: # 업로드 시 크기 제한
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

# AWS S3 설정 (환경 변수로 오버라이드)
aws:
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
    s3:
        bucket-name: ${AWS_S3_BUCKET_NAME:skillary-s3}
        region: ${AWS_S3_REGION:ap-northeast-2}
        base-url: ${AWS_S3_BASE_URL:}  # s3 파일서버 별도 도에인 있는 경우 (없어서 빈값)
