services:
  front:
    env_file: .env.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: next-skillary:1.0
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"